#!/bin/sh
# From QiuSimons

cd /overlay
rm -rf `ls | egrep -v '(upper|.fs_state)'`
cd /overlay/upper
rm -rf `ls | egrep -v '(etc|usr)'`
cd /overlay/upper/usr
rm -rf `ls | egrep -v '(share)'`
cd /overlay/upper/usr/share
rm -rf `ls | egrep -v '(bench.log|shadow)'`
cd /overlay/upper/etc
rm -rf `ls | egrep -v '(config|dae|network|uhttpd.crt|uhttpd.key)'`
cd /overlay/upper/etc/config
rm -rf `ls | egrep -v '(autoreboot|firewall|network|dae|dhcp)'`
sleep 5 && touch /etc/banner && reboot
