#!/bin/sh

[ "$ACTION" = ifup -o "$ACTION" = ifupdate ] || exit 0
[ "$ACTION" = ifupdate -a -z "$IFUPDATE_ADDRESSES" -a -z "$IFUPDATE_DATA" ] && exit 0

logger -t odhcpd "Reloading odhcpd due to $ACTION of $INTERFACE ($DEVICE)"

"/etc/init.d/odhcpd" restart
