#!/bin/sh

#Set default lang
uci set luci.main.lang='en'
uci commit luci

#Timezone UTC+10/+11
uci set system.@system[0].zonename=Australia/Melbourne
uci set system.@system[0].timezone=AEST-10AEDT,M10.1.0,M4.1.0/3
uci commit system

#uhttpd
uci set uhttpd.main.rfc1918_filter=0
uci set uhttpd.main.redirect_https=0
uci set uhttpd.main.http_keepalive=0
uci set uhttpd.main.tcp_keepalive=0
uci set uhttpd.main.script_timeout=65535
uci set uhttpd.main.script_network_timeout=65535
uci commit uhttpd
/etc/init.d/uhttpd restart

#Defalut lan IP
uci set network.lan.ipaddr=192.168.1.1

#Remove IPv6
uci delete network.globals.ula_prefix
uci delete network.lan.ip6assign
uci delete network.wan6
uci delete dhcp.lan.ra
uci delete dhcp.lan.ra_management
uci delete dhcp.lan.dhcpv6
uci delete dhcp.lan.ndp
uci commit dhcp

#Packet Steering and Set Lan MTU
uci set network.globals.packet_steering=1
uci commit network
/etc/init.d/network restart

#Firewall
uci set firewall.@defaults[0].fullcone='1'
uci set firewall.@defaults[0].flow_offloading='1'
uci set firewall.@defaults[0].flow_offloading_hw='0'
uci commit firewall

#SSL
sed -i 's,#devcrypto,devcrypto,g' /etc/ssl/openssl.cnf
sed -i 's,#USE_SOFTDRIVERS = 2,USE_SOFTDRIVERS = 1,g' /etc/ssl/openssl.cnf

#Dnsmasq
sed -i '/log-facility/d' /etc/dnsmasq.conf
echo "log-facility=/dev/null" >> /etc/dnsmasq.conf

#Dae
[ -f '/etc/dae/config.dae' ] && chmod 600 /etc/dae/config.dae

#Others
[ ! -f '/usr/bin/ip' ] && [ -f '/sbin/ip' ] && ln -sf /sbin/ip /usr/bin/ip
[ ! -f '/usr/bin/wget-ssl' ] && [ -f '/usr/bin/wget' ] && ln -sf /usr/bin/wget /usr/bin/wget-ssl
opkg flag hold luci-app-firewall
opkg flag hold firewall
opkg flag hold dnsmasq-full
#sync; echo 3 > /proc/sys/vm/drop_caches

#Flush LuCI cache
rm -rf /tmp/luci-modulecache
rm -f /tmp/luci-indexcache

exit 0
