#!/bin/sh

[ "$ACTION" = ifup ] || exit 1

BOARD=$(cat /tmp/sysinfo/board_name | cut -d , -f2)
logger -t disable-offloading "board = $BOARD"

case $BOARD in
"nanopi-r2"|"nanopi-r2s"|"nanopi-r2c"|"nanopi-neo3")
    logger -t disable-offloading "continue..."
    ;;
*)
    exit 2
esac

logger -t disable-offloading "rk3328 board detected"

ETHTOOL=/usr/sbin/ethtool
[ -f $ETHTOOL ] || exit 3

$ETHTOOL -K eth0 rx off tx off

logger -t disable-offloading "disabed rk3328 ethernet tcp/udp offloading tx/rx"
exit 0
